# Generated by Django 3.2.8 on 2021-12-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('second_name', models.CharField(max_length=225)),
                ('date_of_birth', models.DateField()),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug for theme')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('dimension', models.CharField(max_length=2, verbose_name=[('Вт', 'Ватты'), ('Дж', 'Джоули'), ('Кл', 'Кулоны'), ('Па', 'Паскали'), ('H', 'Ньютоны'), ('Ф', 'Фараты'), ('К', 'Кельвины')])),
                ('formula_img', models.ImageField(upload_to='formulas/author_None/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.author')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.theme')),
            ],
            options={
                'verbose_name': 'Формула',
                'verbose_name_plural': 'Формулы',
            },
        ),
    ]
