# Generated by Django 3.2.8 on 2021-12-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Slug for theme'),
        ),
    ]
